services:
  stats-server:
    build: stats/stats-service
    container_name: stats-service-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING-DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:16-alpine
    container_name: stats-db-container
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING-DATASOURCE_PASSWORD=password

  main-db:
    image: postgres:16-alpine
    container_name: main-db-container
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
